#version: "3.9"
services:
  banco:
    image: postgres:11
    container_name: postgresbrain
    ports:
      - 5432:5432
    networks:
      - teste-bridge 
    environment:
      POSTGRES_PASSWORD: admin
    volumes:
      - ./bancovolumebrain:/var/lib/postgresql/data

  node:
    build:
      context: .
      args:
        PORTA: 3000
    container_name: node_teste
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - teste-bridge 
    command: "npm run start:dev"
    depends_on:
      - banco
  

      
  swagger:
    image: docker.swagger.io/swaggerapi/swagger-ui
    container_name: swagger_brain_ag
    ports:
      - 8081:8080
    networks:
      - teste-bridge 
    environment:
      API_URL: http://localhost:8081/swagger.yml
      BASE_URL: /swagger
      SWAGGER_JSON: /swagger/swagger.yml
    volumes:
      - ./swagger:/swagger
    depends_on:
      - node
      

networks:
  teste-bridge:
    driver: bridge