openapi: 3.0.1
info:
  title: Brain Agriculture 
  description: API Para cadastro de Produtores Rurais
  version: 0.0.1
  # termsOfService: https://mockapi.io
  contact:
    name: Herlessi Nogueira Bezerra
    email: herlessi@gmail.com
    url: https://mockapi.io
  license:
    name: "Lincença: GPLv3"
    url: https://www.gnu.org/licenses/gpl-3.0.html
externalDocs:
  description: Documentação burocrática
  url: https://mockapi.io

servers:
- url: http://localhost:3000/
  description: API de Teste

paths:
  /produtor:
    get:
      summary: Listar Produtores
      tags:
        - Brain AG                               
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                type: object
        400:
          description: Erro
          content:
            application/json:
              schema:
                type: object
    post:
      summary: Criar Novo Produto
      tags:
        - Brain AG 
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                documento:
                  type: string
                  example: "00000000000"
                nomeProdutor:
                  type: string
                  example: "Joao da Silva"                  
                nomefazenda:
                  type: string
                  example: "Por do sol"                  
                cidade:
                  type: string
                  example: "Campinas"                  
                estado:
                  type: string
                  example: "Sao Paulo"                  
                area_fazenda_hecta:
                  type: number
                  example: 10                 
                area_agricultavel_hecta:
                  type: number
                  example: 8                  
                area_vegetacao_hecta:
                  type: number
                  example: 2
                safra:
                  type: number
                  example: 2024
                cultura_plantada:
                  type: string
                  example: "milho"                  
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                type: object
        400:
          description: Erro
          content:
            application/json:
              schema:
                type: object                
  /produtor/{id}:                
    put:
      summary: Atualizar Produtor
      tags:
        - Brain AG 
      parameters:
        - in: path
          name: id
          schema:
            type: number
          required: true
          description: id do Produtor
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                documento:
                  type: string
                  example: "00000000000"
                nomeProdutor:
                  type: string
                  example: "Joao da Silva"                  
                nomefazenda:
                  type: string
                  example: "Por do sol"                  
                cidade:
                  type: string
                  example: "Campinas"                  
                estado:
                  type: string
                  example: "Sao Paulo"                  
                area_fazenda_hecta:
                  type: number
                  example: 10                 
                area_agricultavel_hecta:
                  type: number
                  example: 8                  
                area_vegetacao_hecta:
                  type: number
                  example: 2
                safra:
                  type: number
                  example: 2024
                cultura_plantada:
                  type: string
                  example: "milho"                   
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                type: object
        400:
          description: Erro
          content:
            application/json:
              schema:
                type: object 
    delete:
      summary: Deletar Produtor
      tags:
        - Brain AG 
      parameters:
        - name: id
          in: path
          schema:
            type: number
          required: true
          description: id do Produtor       
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                type: object
        400:
          description: Erro
          content:
            application/json:
              schema:
                type: object                                

